$(document).ready(function() {
  // Sidebar toggle variables
  const openerIcon = "fas fa-angle-double-right";
  const closerIcon = $("#toggleIcon").attr("class");
  const toggleSpeed = 300;
  const visibleEdge = 10;

  // Set inital position of sidebar using above visibleEdge constant
  let leftWhenHidden = (function(edge) {
    let units = $("#sidebar")
      .css("width")
      .match(/\D/g)
      .join("");
    let widthValue = $("#sidebar")
      .css("width")
      .match(/\d+(?:\.\d+)?/g)
      .map(Number);
    widthValue[0] -= edge;
    return "-" + widthValue[0].toString() + units;
  })(visibleEdge);

  // Toggle sidebar
  $("#toggle").click(function() {
    if ($("#toggleIcon").attr("class") == openerIcon) {
      $("#toggleIcon")
        .removeClass(openerIcon)
        .addClass(closerIcon);
      $("#sidebar").animate({ left: 0 }, toggleSpeed);
    } else if ($("#toggleIcon").attr("class") == closerIcon) {
      $("#toggleIcon")
        .removeClass(closerIcon)
        .addClass(openerIcon);
      $("#sidebar").animate({ left: leftWhenHidden }, toggleSpeed);
    }
  });

  // Display map
  mapboxgl.accessToken =
    "pk.eyJ1Ijoic2lnbmlvcmdyYXRpYW5vIiwiYSI6ImNqemcxdHZrNTBkeWUzbXBoZDBicnMxNXEifQ.yBDCU__0UQAqqZDlbzpHgQ";

  const centerLon = -84.212;
  const centerLat = 34.037;

  let map = new mapboxgl.Map({
    container: "map",
    style: "mapbox://styles/mapbox/streets-v9",
    center: [centerLon, centerLat],
    zoom: 12.1
  });

  // Searchbar keyup event
  $("#search").on("keyup", function() {
    clearPromise()
      .then(newSearch)
      .catch(err => console.log(err));
  });

  // Coordinates for bound box
  const lonOffset = 0.076;
  const latOffset = 0.053;
  const minLon = centerLon - lonOffset;
  const minLat = centerLat - latOffset;
  const maxLon = centerLon + lonOffset;
  const maxLat = centerLat + latOffset;

  // Buffers to store places and popups generated by search function
  let popups = [];
  let places = [];

  // Search function declaration
  function newSearch() {
    if ($("#search").val()) {
      // Make API request
      let query = $("#search")
        .val()
        .replace(" ", "%20");

      let url =
        "https://api.mapbox.com/geocoding/v5/mapbox.places/" +
        query +
        `.json?bbox=${minLon},${minLat},${maxLon},${maxLat}&access_token=` +
        mapboxgl.accessToken;

      fetch(url)
        .then(response => response.json())
        .then(jsonResponse => {
          let results = jsonResponse.features;

          // Make array of place names from search results
          populatePlacesBuffer(results);

          // Create index that will be used to forge a connection between popup and sidebar search result
          let resultIndex = 0;

          // Append search results to sidebar, create markers and popups
          places.forEach(place => {
            // Prevent against corner case of more than 5 search results at once
            if ($("#results").find(".search-result").length >= 5) {
              clearPreviousSearch();
            }

            appendToSidebar(place, resultIndex);
            let newPopup = createPopup(place);
            createMarker(place, newPopup);
            resultIndex++;
          });

          // Once popups and sidebar results have been created, display popups on sidebar hover
          createSidebarHandlers();
        });
    }
  }

  /*
  ========================================
    HELPER FUNCTION DECLARATIONS
  ========================================
  */

  // Functions for clearing
  function clearPreviousSearch() {
    $(".mapboxgl-marker").remove();
    $(".search-result").remove();
    $(".mapboxgl-popup").remove();
    popups = [];
    places = [];
  }

  function clearPromise() {
    return new Promise((resolve, reject) => {
      clearPreviousSearch();

      if ($("#results").find(".search-result").length == 0) {
        resolve();
      } else {
        reject("Error: search not clear");
      }
    });
  }

  // Object prototype definition
  function Place(name, address, addressLong, lat, lon) {
    this.name = name;
    this.address = address;
    this.addressLong = addressLong;
    this.lat = lat;
    this.lon = lon;
  }

  // Function to push data from feature results into places buffer
  function populatePlacesBuffer(results) {
    results.forEach(result => {
      let name = result.place_name.split(",").slice(0, 1);
      let address = result.place_name
        .split(",")
        .slice(1, 3)
        .join(",");
      let addressLong = result.place_name
        .split(",")
        .slice(1)
        .join(",")
        .replace(", United States", "");
      let lat = result.geometry.coordinates[1];
      let lon = result.geometry.coordinates[0];

      if (places.length < 5) {
        places.push(new Place(name, address, addressLong, lat, lon));
      }
    });
  }

  // Marker and popup constructors
  function createPopup(place) {
    var popup = new mapboxgl.Popup({
      offset: 25,
      closeButton: false
    }).setHTML(`<h4>${place.name}</h4><p>${place.addressLong}</p>`);

    popups.push(popup);

    return popup;
  }

  function createMarker(place, popup) {
    new mapboxgl.Marker()
      .setLngLat([place.lon, place.lat])
      .setPopup(popup)
      .addTo(map);
  }

  // Function to append result of id="id" to sidebar
  function appendToSidebar(place, id) {
    $("#results").append(`<div class="search-result" id="${id}">
      <h3>${place.name}</h3>
      <p>${place.address}</p>
      </div>`);
  }

  // Function to create sidebar handlers that toggle popup display on hover
  function createSidebarHandlers() {
    function popupThatCorrespondsTo(element) {
      let index = element.id;
      return popups[index];
    }

    $(".search-result").mouseenter(function() {
      let resultPopup = popupThatCorrespondsTo(this);
      if (!resultPopup.isOpen()) {
        resultPopup.addTo(map);
      }
    });
    $(".search-result").mouseleave(function() {
      let resultPopup = popupThatCorrespondsTo(this);
      if (resultPopup.isOpen()) {
        resultPopup.remove();
      }
    });
  }
});
